os:
  - linux

language: c

compiler:
  - gcc

env:
  - WINEARCH=win32 DEPLOY=true
  - WINEARCH=win64 DEPLOY=true
  - WINEARCH="" # WoW64
  - NOCHECK="--nocheck"
  - WINEARCH=win32 CACHE="--cache https://s3.amazonaws.com/fracting/msys2/pack/msys2-pack-20150512_v1_i686.tar.gz"
  - WINEARCH=win64 CACHE="--cache https://s3.amazonaws.com/fracting/msys2/pack/msys2-pack-20150512_v1_x86_64.tar.gz"
  - WINE_STABLE=true

cache: apt

before_install:
  - "export DISPLAY=:99.0"
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 800x600x16"
  - if [ "${WINE_STABLE}" = true ]; then sudo add-apt-repository -y ppa:pipelight/stable; fi
  - if [ "${WINE_STABLE}" != true ]; then sudo add-apt-repository -y ppa:pipelight/daily; fi
  - sudo apt-get update -qq

install:
  - sudo apt-get install -y --install-recommends wine-staging wine-staging-compat
  - sudo apt-get install -y --install-recommends dpkg-dev
  - dpkg-buildpackage -b -us -uc
  - DEB_DIR=`pwd`/..
  - sudo dpkg -i ${DIB_DIR}/*.deb
    #  - MSYS2_SCRIPTS_DEB=msys2-scripts_20150811_all.deb
    #  - wget https://s3.amazonaws.com/fracting/msys2/pack/${MSYS2_SCRIPTS_DEB}
    #  - sudo dpkg -i ${MSYS2_SCRIPTS_DEB}

before_script:
  - msys2-init ${CACHE}
  - if [ "${DEPLOY}" = true ]; then msys2-pack v1; fi

script:
  - svn co https://github.com/fracting/MSYS2-packages/trunk/xz
  - cd xz
  - msys2-shell -c "makepkg -s -f --noconfirm --skippgpcheck ${NOCHECK}"

after_success:
  - cp ${DIB_DIR}/*.deb ${HOME}/msys2-pack

deploy:
  provider: s3
  access_key_id: "AKIAI332BORZKTHFBYBA"
  secret_access_key: "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"
  bucket: "fracting/msys2/pack"
  skip_cleanup: true
  acl: public_read
  local_dir: ${HOME}/msys2-pack
  on:
    condition: ${DEPLOY} = true
