#!/bin/bash

set -x

. /etc/msys2-env

if [ "$1" = "-h" ] || [ "$1" = "--help" ] || [ "$#" = "0" ]
then
    echo Usage: $0 "[DEB_VER]"
    echo Package Wine msys2 bottle.
    exit
fi

DEB_VER=$1

# clean pacman cache
rm -rf ${MSYS_ROOT}/var/cache/pacman/pkg/*

cd ${MSYS_ROOT}/..
NEW_MSYS2_PACKAGE=msys2-${MSYS_VER}_${DEB_VER}_${MSYS_ARCH}
tar zcf ${NEW_MSYS2_PACKAGE}.tar.gz `basename ${MSYS_ROOT}`

mv ${NEW_MSYS2_PACKAGE}.tar.gz ~
cd ~
echo "shasum:"
sha1sum ${NEW_MSYS2_PACKAGE}.tar.gz
ls
