#!/bin/bash

set -e
#set -x

. /etc/msys2-env

DISPLAY=:88.0 WINEDEBUG=-all wineboot # hack - wineboot without display, create wineprefix in a quick way, workaround Travis CI timeout (FIXME)

MSYS2_CACHE=~/.cache/msys2
if ! test -d ${MSYS2_CACHE}
then
    mkdir -p ${MSYS2_CACHE}
fi

MSYS2_INSTALLER=msys2-base-${MSYS_ARCH}-${MSYS_VER}.tar.xz

if ! test -f ${MSYS2_CACHE}/${MSYS2_INSTALLER}
then
    cd ${MSYS2_CACHE}
    wget --inet4-only http://mirrors4.ustc.edu.cn/msys2/Base/${MSYS_ARCH}/${MSYS2_INSTALLER}
fi

cd $WINEPREFIX/drive_c
tar xf ${MSYS2_CACHE}/${MSYS2_INSTALLER}
