#!/bin/sh

set -e
set -x

msys2-install
msys2-wrapper "echo restart"
msys2-wrapper "pacman -Sy"
msys2-wrapper "pacman -S --needed msys2-runtime pacman pacman-mirrors"
msys2-wrapper "pacman -Sy"
msys2-wrapper "pacman -Su"
