#!/bin/sh

set -e
set -x

. /etc/msys2-env

export MSYSTEM=MSYS
export WINEDEBUG=fixme-all
command=$*
rm -f $MSYS_ROOT/$HOME/typescript
(wineconsole $MSYS_ROOT/usr/bin/bash.exe -l -e -c "script -q -f -e -c \"$command\"";echo $? > exit_code)&
#(wineconsole $MSYS_ROOT/usr/bin/bash.exe -l -e -c \"script -q -f -e -c ls\";echo $? > exit_code)&
tail -f --retry --pid=$! $MSYS_ROOT/$HOME/typescript
return $(cat exit_code)
