#!/bin/bash

set -e
#set -x

. /etc/msys2-env

msys2-install
msys2-wrapper "echo restart"

# make a symbolic link from unix $HOME to msys2 $HOME
if test ${MSYS_ROOT} && ! test -L ${MSYS_ROOT}${HOME}
then
    mv -v ${MSYS_ROOT}${HOME} ${MSYS_ROOT}${HOME}.bak
    ln -sfv ${HOME} ${MSYS_ROOT}${HOME}
fi

# Set ustc mirror
#echo "Server = http://mirrors.ustc.edu.cn/msys2/REPOS/MSYS2/\$arch" >> ${MSYS_ROOT}/etc/pacman.d/mirrorlist.msys
#echo "Server = http://mirrors.ustc.edu.cn/msys2/REPOS/MINGW/i686" >> ${MSYS_ROOT}/etc/pacman.d/mirrorlist.mingw32
#echo "Server = http://mirrors.ustc.edu.cn/msys2/REPOS/MINGW/x86_64" >> ${MSYS_ROOT}/etc/pacman.d/mirrorlist.mingw64

# Set new msys2 mirror
echo "Server = http://45.59.69.178/msys/\$arch" > ${MSYS_ROOT}/etc/pacman.d/mirrorlist.msys
echo "Server = http://45.59.69.178/mingw/i686" > ${MSYS_ROOT}/etc/pacman.d/mirrorlist.mingw32
echo "Server = http://45.59.69.178/mingw/x86_64" > ${MSYS_ROOT}/etc/pacman.d/mirrorlist.mingw64

msys2-wrapper "pacman -Sy"
msys2-wrapper "pacman -Sy"
msys2-wrapper "pacman -S --needed --noconfirm msys2-runtime pacman pacman-mirrors"
msys2-wrapper "pacman -S --needed --noconfirm msys2-runtime pacman pacman-mirrors"
msys2-wrapper "pacman -Sy"
msys2-wrapper "pacman -Sy"
msys2-wrapper "pacman -Su --noconfirm"
msys2-wrapper "pacman -Su --noconfirm"
msys2-wrapper "pacman -S --needed --noconfirm msys2-devel base-devel"
msys2-wrapper "pacman -S --needed --noconfirm msys2-devel base-devel"

msys2-wrapper "pacman -S --needed --noconfirm wget"
msys2-wrapper "pacman -S --needed --noconfirm wget"

msys2-wrapper "pacman -S --needed --noconfirm mingw-w64-i686-xz"
msys2-wrapper "pacman -S --needed --noconfirm mingw-w64-i686-xz"

# replace xz -T0 by xz -T1, workaround wine-staging bug 241 - https://bugs.wine-staging.com/show_bug.cgi?id=241
echo replace msys2 xz by mingw32 xz, workaround wine-staging bug 241
sed -i 's/xz -c -z -T0 -/xz -c -z -T1 -/' ${MSYS_ROOT}/etc/makepkg.conf
sed -i 's/xz -c -z -T0 -/xz -c -z -T1 -/' ${MSYS_ROOT}/etc/makepkg_mingw32.conf
sed -i 's/xz -c -z -T0 -/xz -c -z -T1 -/' ${MSYS_ROOT}/etc/makepkg_mingw64.conf

# replace msys2 xz by mingw32 xz, workaround wine-staging bug 394 - https://bugs.wine-staging.com/show_bug.cgi?id=394
echo replace msys2 xz by mingw32 xz, workaround wine-staging bug 394
sed -i 's/xz -d -c/\/mingw32\/bin\/xz -d -c/' ${MSYS_ROOT}/usr/bin/autopoint

# disable autom4te flock, workaround wine staging bug 466 in travis ci old kernel - https://bugs.wine-staging.com/show_bug.cgi?id=466
sed -i "s/flock_implemented = 'yes'/flock_implemented = 'no'/" ${MSYS_ROOT}/usr/bin/autom4te
